###
POST http://localhost:8080/HiberApp/book/create?title=potop&rating=8&description=dobre

###
POST http://localhost:8080/HiberApp/book/createWithPublisher?title=potop&rating=8&description=dobre&publisherName=Ossolineum

###
POST http://localhost:8080/HiberApp/book/createWithAuthors?title=potop&rating=8&description=dobre&authorsCsv=Ala,Makota

###
GET http://localhost:8080/HiberApp/author/1

###
GET http://localhost:8080/HiberApp/book

###
GET http://localhost:8080/HiberApp/book/withMinRating/7

###
GET http://localhost:8080/HiberApp/validation/example1
Accept-Language:en-EN,en
